### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  İki işlevin birleşimini döndürür.


  $ Ve $g $ $f iki işlev verildiğinde, $f \circ g $ temsil eden yeni bir işlev döndürür.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Uygulanacak ikinci işlev.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Uygulanacak ilk işlev.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: $, $F (g (x)) = h (x) $ $x tüm girişler için $h $ gibi yeni bir işlev.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Uygulanacak ilk işlevin giriş türü.
- uid: "'U"
  summary: Uygulanacak ilk işlevin çıkış türü ve uygulanacak ikinci işlevin giriş türü.
- uid: "'V"
  summary: Uygulanacak ikinci işlevin çıkış türü.
metadata:
  ms.openlocfilehash: e62937fd42cb4067ca7a7947cac29a9ef539da6c
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89356754"
