### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  İki işlev birleşimini üretir.


  Diğer bir deyişle, $ ve $g $ $f iki işlev verildiğinde, $f \circ g $ temsil eden yeni bir işlev döndürür.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Uygulanacak ikinci işlev.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Uygulanacak ilk işlev.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: $, $F (g (x)) = h (x) $ $x tüm girişler için $h $ gibi yeni bir işlev.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Uygulanacak ilk işlevin giriş türü.
- uid: "'U"
  summary: Uygulanacak ilk işlevin çıkış türü ve uygulanacak ikinci işlevin giriş türü.
- uid: "'V"
  summary: Uygulanacak ikinci işlevin çıkış türü.
metadata:
  ms.openlocfilehash: 69fbd6a4fafbc61a63e41257b7100303fd48d4d4
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: tr-TR
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73223080"
